### ISSUE TITLE
VGMDB Importer on latest Firefox gives parsing error.

### ISSUE THREAD

**Issue by Tenome** [murdos/musicbrainz-userscripts#470]
> Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 2 column 5 of the JSON data
    parseApi moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/ Import VGMdb releases into MusicBrainz.user.js#70:590
    onload moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/ Import VGMdb releases into MusicBrainz.user.js#70:583
    HttpRequested moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
    HttpRequested moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
    onHandle moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
    c moz-extension://65958e12-29a0-4ed6-88f3-af58d20de004/sandbox/injected-web.js:1
105445 line 1 > injectedScript:590:26
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/JSON_bad_parse

I tried it on a portable Chrome installation and it gave this message. So perhaps VGMDB updated again?

> 105445:2 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 5
    at JSON.parse (<anonymous>)
    at parseApi (Import VGMdb releases into MusicBrainz.user.js:590:26)
    at onload (Import VGMdb releases into MusicBrainz.user.js:583:29)
    at injected-web.js:1:12246
    at Object.HttpRequested (injected-web.js:1:12286)
    at onHandle (injected-web.js:1:3498)
    at HTMLDocument.<anonymous> (injected-web.js:1:13823)
	
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
Page layout may be unexpected due to Quirks Mode

**Comment by ResidualBlood** [comment]
same error in Chrome  100.0.4896.75
```
Uncaught SyntaxError: Unexpected token < in JSON at position 5
    at JSON.parse (<anonymous>)
    at parseApi (userscript.html?name=Import%2520VGMdb%2520releases%2520into%2520MusicBrainz.user.js&id=xxx:26)
    at Object.onload (userscript.html?name=Import%2520VGMdb%2520releases%2520into%2520MusicBrainz.user.js&id=xxx:29)
    at it (<anonymous>:14:1074)
    at Object.s.onload (<anonymous>:51:4)
    at it (<anonymous>:14:1074)
    at <anonymous>:18:278
    at it (<anonymous>:14:1074)
    at a (<anonymous>:3:446)
    at <anonymous>:4:111
```

**Comment by Tenome** [comment]
@ResidualBlood Another MB user deployed a backup of the VGMDB server (which has been down for over 2 weeks now) since it's open source. Replace line 21 or so with the following:

`    let apiUrl = window.location.href.replace('net', 'info').concat('', '?format=json');
//  Temporary server since VGMDB.info has been down for a while
    apiUrl = apiUrl.replace('https://vgmdb.info/', 'https://vgmdb-y-young.cloud.okteto.net/');`

**Comment by ResidualBlood** [comment]
> @ResidualBlood Another MB user deployed a backup of the VGMDB server (which has been down for over 2 weeks now) since it's open source. Works as intended now. Replace line 21 or so with the following:
> 
> ```js
> let apiUrl = window.location.href.replace('net', 'info').concat('', '?format=json');
> //  Temporary server since VGMDB.info has been down for a while
> apiUrl = apiUrl.replace('https://vgmdb.info/', 'https://vgmdb-y-young.cloud.okteto.net/');
> ```
> 
> puu.sh/IUo0S/05189270cb.png

Thank you replay, after replace it can importer

**Comment by dxman** [comment]
It looks like vgmdb.info is currently down again? I just tried the alternate URL mentioned above, and that is also unavailable.

**Comment by Fabe56** [comment]
Do not work either with Tampermonkey v5.1.0 for Microsoft Edge.

**Comment by esahin** [comment]
The script still doesn't work because of the API returns. Neither the [vgmdb.info](https://vgmdb.info/) nor the [vgmdb-y-young.cloud.okteto.net](https://vgmdb-y-young.cloud.okteto.net/) sites are working.

**Comment by Tenome** [comment]
I haven't used this in forever so I don't really remember which script I made this thread for, but I have a script by Ame that seems to work still. It's somewhere in the MB forum, so here's the script.

![Image](https://github.com/user-attachments/assets/d6682cb2-750f-4ff1-9162-44e91d80b6a2)

https://pastebin.com/rJRhVFcZ
